### ISSUE TITLE
Hello, thanks suggestions for TLS

### ISSUE THREAD

**Issue by r3k2** [PennockTech/fingerd#1]
Hello,
 I was looking for a fingerd server, I am a systems/cybersecurity engineer, so I am not that great at coding big things, so this is wonderful that you have written this, I have installed this locally and test it, works fine.
If I can help, I can create systemd files even do I will recommend everyone to run as user from the start,  but we can create systemctl --user files and have two options.
I also wrote a small doc and instead of changing the permissions for /home/users folders I created a /home/fingerd that users can have access to (in my case just me) and inside there expose .plan .project etc.
- https://man.sr.ht/~rek2/Hispagatos-wiki/finger_protocolo.md

That is a very raw thing I wrote now as I was testing the whole thing.
- How hard will  be to add TLS support?
- I think if done right and with some changes, as you already did some finger can be revamped just like gemini has done for gopher specially nowadays that lot of us are going back to decentralized services like the modern fediverse or old USENET.

**Comment by philpennock** [comment]
Hi, thanks for your interest.  :)

So, the big issue with TLS is defining how it works and getting clients supporting it, and downgrading correctly without introducing security problems when a server doesn't support TLS.

I think it's a good idea to ask "why a dedicated protocol?" and "what tools should support this?"; to me, finger is an interesting historical approach which it's sometimes useful to support, but not something to use as a foundation for a new ecosystem.

It's probably a better idea to figure out if https or gemini with standard site-layout schemas are a good fit for your requirements.  For instance, for retrieving OpenPGP keys we already have WKD: <https://wiki.gnupg.org/WKD>
which uses a schema to let clients build a URL under `/.well-known/openpgpkey/` and retrieve keys that way.  This already has client support in tools such as GnuPG and various email clients today, so won't require changing every client on the Internet.
